title: "My GitHub Page"
description: "Welcome to my GitHub Page powered by Jekyll."
author: "Your Name"
url: "https://daoductu112.github.io"
baseurl: "/Tu_page"  # Leave blank for GitHub Pages
# Replace with your GitHub Pages URL